-- INICIO BLOQUE: CREACION TABLA AUDITORIAS
-- REGISTRA TRAZABILIDAD DE ACCIONES CRUD Y EVENTOS DE ACCESO/LOGOUT.
CREATE TABLE IF NOT EXISTS auditorias (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fechaevento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idusuario VARCHAR(20) NULL,
    accion VARCHAR(20) NOT NULL,
    tablaafectada VARCHAR(100) NULL,
    idregistro VARCHAR(50) NULL,
    datosantes JSON NULL,
    datosdespues JSON NULL,
    CONSTRAINT chkauditoriasaccion
        CHECK (accion IN ('CREAR', 'LEER', 'ACTUALIZAR', 'ELIMINAR', 'ACCESO', 'LOGOUT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA AUDITORIAS

-- INICIO BLOQUE: CREACION TABLA USUARIOS
-- DEFINE LA ESTRUCTURA BASE DE AUTENTICACION Y DATOS GENERALES DE USUARIO.
CREATE TABLE IF NOT EXISTS usuarios (
    id VARCHAR(20) PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(20) NOT NULL,
    clavehash VARCHAR(255) NOT NULL,
    perfil VARCHAR(20) NOT NULL,
    idtienda INT UNSIGNED NULL,
    provincia VARCHAR(30) NULL,
    canton VARCHAR(50) NULL,
    distrito VARCHAR(50) NULL,
    direccion VARCHAR(255) NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkusuariostienda
        CHECK (
            (perfil = 'TIENDA' AND idtienda IS NOT NULL)
            OR (perfil IN ('CLIENTE', 'ADMINISTRADOR') AND idtienda IS NULL)
        ),
    CONSTRAINT chkusuariosperfil
        CHECK (perfil IN ('CLIENTE', 'TIENDA', 'ADMINISTRADOR')),
    CONSTRAINT chkusuariosestado
        CHECK (estado IN ('ACTIVO', 'BLOQUEADO', 'INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA USUARIOS

-- INICIO BLOQUE: CREACION TABLA TIENDAS
-- DEFINE EL CATALOGO DE TIENDAS AFILIADAS Y LA MARCA DE TIENDA QUE ACTUA COMO CENTRO DE DISTRIBUCION.
CREATE TABLE IF NOT EXISTS tiendas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    provincia VARCHAR(30) NOT NULL,
    canton VARCHAR(50) NOT NULL,
    distrito VARCHAR(50) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    -- 1 SI LA TIENDA ACTUA COMO CENTRO DE DISTRIBUCION (NOMBRE TECNICO DE COLUMNA: eshub).
    eshub TINYINT(1) NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chktiendaseshub
        CHECK (eshub IN (0, 1)),
    CONSTRAINT chktiendasestado
        CHECK (estado IN ('ACTIVO', 'BLOQUEADO', 'INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA TIENDAS

-- INICIO BLOQUE: CREACION TABLA EVALUACIONES
-- DEFINE LA EVALUACION UNICA POR USUARIO EMITIDA POR UNA TIENDA.
CREATE TABLE IF NOT EXISTS evaluaciones (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idusuario VARCHAR(20) NOT NULL,
    idtienda INT UNSIGNED NOT NULL,
    rapidez TINYINT UNSIGNED NOT NULL,
    confianza TINYINT UNSIGNED NOT NULL,
    seguridad TINYINT UNSIGNED NOT NULL,
    calidad TINYINT UNSIGNED NOT NULL,
    listanegra TINYINT(1) NOT NULL DEFAULT 0,
    motivolistanegra VARCHAR(255) NULL,
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkevaluacionesrapidez
        CHECK (rapidez BETWEEN 0 AND 5),
    CONSTRAINT chkevaluacionesconfianza
        CHECK (confianza BETWEEN 0 AND 5),
    CONSTRAINT chkevaluacionesseguridad
        CHECK (seguridad BETWEEN 0 AND 5),
    CONSTRAINT chkevaluacionescalidad
        CHECK (calidad BETWEEN 0 AND 5),
    CONSTRAINT chkevaluacioneslistanegra
        CHECK (listanegra IN (0, 1)),
    CONSTRAINT chkevaluacionesmotivo
        CHECK (
            (listanegra = 1 AND motivolistanegra IS NOT NULL)
            OR (listanegra = 0)
        ),
    CONSTRAINT unqevaluacionesusuario UNIQUE (idusuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA EVALUACIONES

-- INICIO BLOQUE: CREACION TABLA BINDERS
-- DEFINE EL CONTENEDOR DE BINDER POR USUARIO Y JUEGO TCG.
CREATE TABLE IF NOT EXISTS binders (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idusuario VARCHAR(20) NOT NULL,
    juego VARCHAR(50) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    descripcion VARCHAR(255) NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkbindersestado
        CHECK (estado IN ('ACTIVO', 'BLOQUEADO', 'INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA BINDERS

-- INICIO BLOQUE: CREACION TABLA PRODUCTOS BINDER
-- DEFINE LAS CARTAS REGISTRADAS DENTRO DE CADA BINDER.
CREATE TABLE IF NOT EXISTS productos_binder (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idbinder BIGINT UNSIGNED NOT NULL,
    nombrecarta VARCHAR(150) NOT NULL,
    expansion VARCHAR(100) NULL,
    numerocarta VARCHAR(40) NULL,
    rareza VARCHAR(50) NULL,
    idioma VARCHAR(30) NULL,
    condicion VARCHAR(30) NULL,
    cantidad INT UNSIGNED NOT NULL,
    precioventa DECIMAL(12,2) NOT NULL,
    tipomoneda VARCHAR(20) NOT NULL,
    publicado TINYINT(1) NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkproductosbindercantidad
        CHECK (cantidad >= 1),
    CONSTRAINT chkproductosbindertipomoneda
        CHECK (tipomoneda IN ('COLONES', 'DOLARES')),
    CONSTRAINT chkproductosbinderpublicado
        CHECK (publicado IN (0, 1)),
    CONSTRAINT chkproductosbinderestado
        CHECK (estado IN ('ACTIVO', 'BLOQUEADO', 'INACTIVO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA PRODUCTOS BINDER

-- INICIO BLOQUE: CREACION TABLA IMAGENES PRODUCTO
-- DEFINE EL REGISTRO DE IMAGENES ASOCIADAS A CADA CARTA.
CREATE TABLE IF NOT EXISTS imagenes_producto (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idproducto BIGINT UNSIGNED NOT NULL,
    nombreimagen VARCHAR(255) NOT NULL,
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA IMAGENES PRODUCTO

-- INICIO BLOQUE: CREACION TABLA ENVIOS
-- DEFINE LA CABECERA DEL PROCESO DE ENVIO ENTRE REMITENTE Y DESTINATARIO.
-- LA CLAVE PRIMARIA ES EL NUMERO DE RASTREO: SE ASIGNA EN APLICACION (NO AUTO_INCREMENT).
-- FORMATO OBLIGATORIO DEL ID: PREFIJO CRE + AAAAMMDDHHMMSS (14 DIGITOS), SIN GUIONES (17 CARACTERES).
CREATE TABLE IF NOT EXISTS envios (
    id VARCHAR(17) PRIMARY KEY,
    idremitente VARCHAR(20) NOT NULL,
    iddestinatario VARCHAR(20) NOT NULL,
    idtiendaorigen INT UNSIGNED NOT NULL,
    idtiendadestino INT UNSIGNED NOT NULL,
    -- ID TIENDA QUE CUMPLE ROL DE CENTRO DE DISTRIBUCION (NOMBRE TECNICO DE COLUMNA: idhub).
    idhub INT UNSIGNED NULL,
    -- GUARDA LA RUTA ELEGIDA DEL CATALOGO rutas (DATA-DRIVEN: LOCAL, REMOTO, EN TIENDA, ...).
    -- LONGITUD ALINEADA A rutas.nombre (VARCHAR(40)). LOS VALORES VALIDOS SE CONTROLAN EN APLICACION CONTRA rutas ACTIVAS (SIN CHECK FIJO).
    formaenvio VARCHAR(40) NOT NULL,
    montoapagar DECIMAL(12,2) NOT NULL,
    estado VARCHAR(80) NOT NULL,
    CONSTRAINT chkenviosidrastreo
        CHECK (id REGEXP '^CRE[0-9]{14}$'),
    CONSTRAINT chkenviosmontoapagar
        CHECK (montoapagar >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA ENVIOS

-- INICIO BLOQUE: CREACION TABLA PAQUETES
-- DEFINE LOS PAQUETES FISICOS QUE PERTENECEN A CADA ENVIO.
CREATE TABLE IF NOT EXISTS paquetes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idenvio VARCHAR(17) NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    descripcion VARCHAR(255) NULL,
    cantidad INT UNSIGNED NOT NULL,
    valordeclarado DECIMAL(12,2) NOT NULL,
    CONSTRAINT chkpaquetesidenviorastreo
        CHECK (idenvio REGEXP '^CRE[0-9]{14}$'),
    CONSTRAINT chkpaquetestipo
        CHECK (tipo IN ('SOBRE', 'CAJA', 'BOLSA')),
    CONSTRAINT chkpaquetescantidad
        CHECK (cantidad >= 1),
    CONSTRAINT chkpaquetesvalordeclarado
        CHECK (valordeclarado >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA PAQUETES

-- INICIO BLOQUE: CREACION TABLA MOVIMIENTOS ENVIO
-- DEFINE LA TRAZABILIDAD DE ACCIONES Y EVENTOS DE CADA ENVIO.
CREATE TABLE IF NOT EXISTS movimientos_envio (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idenvio VARCHAR(17) NOT NULL,
    accion VARCHAR(60) NOT NULL,
    detalle VARCHAR(255) NULL,
    guiaexterna VARCHAR(80) NULL,
    idtienda INT UNSIGNED NOT NULL,
    idusuario VARCHAR(20) NOT NULL,
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkmovimientosenvioidenviorastreo
        CHECK (idenvio REGEXP '^CRE[0-9]{14}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA MOVIMIENTOS ENVIO

-- INICIO BLOQUE: CREACION TABLA IMAGENES ENVIO
-- DEFINE LAS IMAGENES DE EVIDENCIA ASOCIADAS A ENVIOS Y PAQUETES.
CREATE TABLE IF NOT EXISTS imagenes_envio (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idenvio VARCHAR(17) NOT NULL,
    idpaquete BIGINT UNSIGNED NOT NULL,
    nombreimagen VARCHAR(255) NOT NULL,
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkimagenvioidenviorastreo
        CHECK (idenvio REGEXP '^CRE[0-9]{14}$')
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA IMAGENES ENVIO

-- INICIO BLOQUE: CREACION TABLA INCIDENCIAS
-- DEFINE EL REGISTRO PRINCIPAL DE INCIDENCIAS ASOCIADAS A CADA ENVIO.
CREATE TABLE IF NOT EXISTS incidencias (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idenvio VARCHAR(17) NOT NULL,
    tipoincidencia VARCHAR(60) NOT NULL,
    estadoincidencia VARCHAR(30) NOT NULL,
    detalleinicial VARCHAR(255) NOT NULL,
    idusuarioreporta VARCHAR(20) NOT NULL,
    idtiendareporta INT UNSIGNED NOT NULL,
    fechareporte DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechacierre DATETIME NULL,
    CONSTRAINT chkincidenciasidenviorastreo
        CHECK (idenvio REGEXP '^CRE[0-9]{14}$'),
    CONSTRAINT chkincidenciasestado
        CHECK (estadoincidencia IN ('INCIDENCIA REPORTADA', 'INCIDENCIA RESUELTA', 'INCIDENCIA CERRADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA INCIDENCIAS

-- INICIO BLOQUE: CREACION TABLA ACTUALIZACIONES INCIDENCIA
-- DEFINE EL HISTORIAL DE ACTUALIZACIONES Y CAMBIOS DE ESTADO DE CADA INCIDENCIA.
CREATE TABLE IF NOT EXISTS actualizaciones_incidencia (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idincidencia BIGINT UNSIGNED NOT NULL,
    estadoincidencia VARCHAR(30) NOT NULL,
    detalleactualizacion VARCHAR(255) NOT NULL,
    idusuarioactualiza VARCHAR(20) NOT NULL,
    idtiendaactualiza INT UNSIGNED NOT NULL,
    fechaactualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkactualizacionesincidenciaestado
        CHECK (estadoincidencia IN ('INCIDENCIA REPORTADA', 'INCIDENCIA RESUELTA', 'INCIDENCIA CERRADA'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA ACTUALIZACIONES INCIDENCIA

-- INICIO BLOQUE: CREACION TABLA CONSOLIDADOS
-- DEFINE CADA SALIDA AGRUPADA DE PAQUETES POR TRAMO LOGISTICO.
-- LA CLAVE PRIMARIA ES CODIGO DE RASTREO: SE ASIGNA EN APLICACION (NO AUTO_INCREMENT).
-- FORMATO OBLIGATORIO DEL ID: PREFIJO CRC + AAAAMMDDHHMMSS (14 DIGITOS), SIN GUIONES (17 CARACTERES).
CREATE TABLE IF NOT EXISTS consolidados (
    id VARCHAR(17) PRIMARY KEY,
    tipotramo VARCHAR(60) NOT NULL,
    idtiendaorigen INT UNSIGNED NOT NULL,
    idtiendadestino INT UNSIGNED NOT NULL,
    idcentrodistribucion INT UNSIGNED NOT NULL,
    guiaexterna VARCHAR(80) NULL,
    estado VARCHAR(30) NOT NULL,
    fechasalida DATETIME NULL,
    fecharecepcion DATETIME NULL,
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkconsolidadosidrastreo
        CHECK (id REGEXP '^CRC[0-9]{14}$'),
    CONSTRAINT chkconsolidadostipotramo
        CHECK (tipotramo IN ('ORIGEN A CENTRO DE DISTRIBUCION', 'CENTRO DE DISTRIBUCION A DESTINO'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA CONSOLIDADOS

-- INICIO BLOQUE: CREACION TABLA DETALLE CONSOLIDADOS
-- DEFINE LOS PAQUETES Y ENVIOS INCLUIDOS EN CADA CONSOLIDADO.
CREATE TABLE IF NOT EXISTS detalle_consolidados (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idconsolidado VARCHAR(17) NOT NULL,
    idenvio VARCHAR(17) NOT NULL,
    idpaquete BIGINT UNSIGNED NOT NULL,
    recibidocorrecto TINYINT(1) NOT NULL DEFAULT 0,
    observacionrecepcion VARCHAR(255) NULL,
    fecharecepcion DATETIME NULL,
    CONSTRAINT chkdetalleconsolidadosidconsolidadorastreo
        CHECK (idconsolidado REGEXP '^CRC[0-9]{14}$'),
    CONSTRAINT chkdetalleconsolidadosidenviorastreo
        CHECK (idenvio REGEXP '^CRE[0-9]{14}$'),
    CONSTRAINT chkdetalleconsolidadosrecibidocorrecto
        CHECK (recibidocorrecto IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA DETALLE CONSOLIDADOS

-- INICIO BLOQUE: CREACION TABLA RUTAS
-- CATALOGO DE TIPOS DE RUTA SEGUN CERCANIA AL HUB (LOCAL/REMOTO/...); DEFINE EL MEDIO DE ENVIO Y SI EXIGE GUIA EXTERNA.
-- LOS VALORES SE ADMINISTRAN COMO DATOS (SIN CHECK FIJO EN nombre) PARA SUMAR TIPOS NUEVOS SIN ALTERAR LA ESTRUCTURA.
-- SE DEFINE ANTES DE tarifas PORQUE ESTA LA REFERENCIA POR CLAVE FORANEA.
CREATE TABLE IF NOT EXISTS rutas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL,
    medioenvio VARCHAR(80) NOT NULL,
    exigeguiaexterna TINYINT(1) NOT NULL DEFAULT 0,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO',
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chkrutasexigeguia
        CHECK (exigeguiaexterna IN (0, 1)),
    CONSTRAINT chkrutasestado
        CHECK (estado IN ('ACTIVO', 'INACTIVO')),
    CONSTRAINT unqrutanombre UNIQUE (nombre)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA RUTAS

-- INICIO BLOQUE: CREACION TABLA TARIFAS
-- DEFINE LA TARIFA DE ENVIO POR TIENDA Y TIPO DE RUTA (FK rutas) PARA CALCULAR montoapagar.
CREATE TABLE IF NOT EXISTS tarifas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    idtienda INT UNSIGNED NOT NULL,
    idruta INT UNSIGNED NOT NULL,
    preciobase DECIMAL(12,2) NOT NULL,
    precioporpaquete DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    fecharegistro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chktarifasprecios
        CHECK (preciobase >= 0 AND precioporpaquete >= 0),
    CONSTRAINT unqtarifatiendaruta UNIQUE (idtienda, idruta),
    CONSTRAINT fktarifastiendas
        FOREIGN KEY (idtienda) REFERENCES tiendas(id),
    CONSTRAINT fktarifasrutas
        FOREIGN KEY (idruta) REFERENCES rutas(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;
-- FIN BLOQUE: CREACION TABLA TARIFAS

